# Unit I: Essential Probability {-}

Probability is the field within mathematics that studies and models random processes.  In contrast, Statistics is a discipline separate from mathematics that uses data to make inference on a population.  Like many other disciplines (e.g., Engineering and the Sciences), while Statistics is a separate discipline, the theory underlying the discipline relies heavily on mathematics; for Statistics, probability plays a pivotal role.  In fact, we once heard an author describe the Bayesian framework as "probability in action."  The key components of a Bayesian approach to inference involve characterizing uncertainty and variability.  And, Probability can be used to develop analytical models to describe that uncertainty and variability.  A firm foundation in probability is necessary to approach inference from a Bayesian perspective.

This unit is not a replacement for a text in Probability; instead, it provides a brief review of key aspects of a Probability course that will be most frequently referenced in the remainder of the text.  Our interest is in illustrating how Probability is applied to support statistical methodology.  While we assume the reader has taken a course in Probability, we review key results as needed.  As this is meant to be used in a Statistics course, our goals are much different than those of a mathematician.  Instead of a rigorous treatment of Probability theory (axioms, etc.), our focus is on the application of Probability to Statistics.
